### ISSUE TITLE
DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm silkscreen has wrong pin 1 indication

### ISSUE THREAD

**Issue by mansr** [KiCad/kicad-footprints#1962]
The pin 1 indication on the silkscreen of DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm is on the wrong side. See screenshot below:
![DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm](https://user-images.githubusercontent.com/322231/68704675-944b3480-0584-11ea-9931-f122cb086d7a.png)

Compare to the EP1.55x2.48mm variant:
![DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2 48mm](https://user-images.githubusercontent.com/322231/68704671-93b29e00-0584-11ea-9f87-98f61b7b60da.png)

**Comment by JacobEFO** [comment]
Hi @mansr,
I have stumbled upon the exact same issue as you: https://github.com/pointhi/kicad-footprint-generator/issues/278

However for non-gullwing packages it is standard to have a missing line at the pin 1 designator, just as the upper footprint you illustrate. However, that would in turn mean, that your second footprint is not shown according to KLC.

However, because of the amount of work, fixing the non-gullwing package footprints is just on-going work and should eventually be fixed.

Disclaimer: Not a librarian, so if you prefer more elaboration. I'm confident the librarians will chime in.

**Comment by poeschlr** [comment]
@JacobEFO is correct. The upper footprint is the one that complies with IPC which is what the KLC suggests to use. See screenshot in https://kicad-pcb.org/libraries/klc/F5.1/ (The bottom right one is of a DFN footprint)

**Comment by mansr** [comment]
Well, that's not confusing at all. Shouldn't all DFN footprints at least use the same convention? Otherwise it all becomes rather pointless.

**Comment by JacobEFO** [comment]
> Well, that's not confusing at all. Shouldn't all DFN footprints at least use the same convention? Otherwise it all becomes rather pointless.

You're absolutely right, they should. 
But unfortunately such extensive work takes time, and as you may be able to see, maintaining such large repositories, that we all gladly utilize, takes quite a while. 
I reckon, if this is not set for a specific milestone, that any help in this regard will be greatly appreciated.

**Comment by chschlue** [comment]
BTW:
Both FPs shown above don't meet the current standard (one has a roundrect EP, the other has rectangular pads.)
The first has to be regenerated, the second added to the generator.

**Comment by poeschlr** [comment]
@chschlue we have done this switch to rectangular center pad after the last release so only users who manually download the libs have them.

**Comment by chschlue** [comment]
@poeschlr Ah, yes. My mistake.

DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm is already fixed in master.
However, DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2.48mm is hand drawn (in case anybody wants to add it to the generator size definitions at https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml)

**Comment by poeschlr** [comment]
Nearly all DFNs are still not in the generator. I suspect it will take at least a man month (160 man-hours) of work to go through all of them (most of the time will be used to find datasheets and check if the symbols that use the current footprints are assigned the correct ones.)
